version: '3.8'
services:

    ############################
    #PROCESSING SERVICE
    ############################
    processing-service:
      build: src/processing_service
      command: uvicorn main:app --host 0.0.0.0 --reload
      ports:
        - 8000:8000
      env_file:
        - .env
      volumes: 
        - shared-resources:/shared

    processing_worker:
      build: ./src/processing_service
      command: celery -A tasks worker -Q processing --loglevel=INFO
      env_file:
        - .env
      volumes: 
        - shared-resources:/shared
      depends_on:
        - redis

    redis:
      image: redis:latest
      ports:
        - '6379:6379'

    flower:
      build: ./src/processing_service
      command: celery -A tasks flower --port=5555
      ports:
        - 5000:5555
      env_file:
        - .env
      depends_on:
        - redis

volumes:
  shared-resources: 