version: '3.8'
services:

    ############################
    #PROCESSING SERVICE
    ############################
    processing-api:
      build: src/processing_service
      command: uvicorn main:app --host 0.0.0.0 --reload
      ports:
        - 8001:8000
      env_file:
        - .env
      volumes: 
        - shared-resources:/shared

    processing-worker:
      build: ./src/processing_service
      command: celery -A tasks worker -Q processing --loglevel=INFO
      env_file:
        - .env
      volumes: 
        - shared-resources:/shared
      depends_on:
        - redis

    flower:
      build: ./src/processing_service
      command: celery -A tasks flower --port=5555
      ports:
        - 5000:5555
      env_file:
        - .env
      depends_on:
        - redis


    ############################
    #UPLOAD SERVICE
    ############################
    upload-api:
      build: src/upload_service
      command: uvicorn main:app --host 0.0.0.0 --reload
      ports:
        - 8002:8000
      env_file:
        - .env
      volumes: 
        - shared-resources:/shared


    redis:
      image: redis:latest
      ports:
        - '6379:6379'


    
volumes:
  shared-resources: 